package env

const (
	SITER_CONFIG_DIRECTORY = "SITER_CONFIG_DIRECTORY"
	SITER_CACHE_DIRECTORY  = "SITER_CACHE_DIRECTORY"
	XDG_CONFIG_HOME        = "XDG_CONFIG_HOME"
	WINDOW_USER_PROFILE    = "USERPROFILE"
)
